Location:
  # We use two similar munges here -- one for exact matches, which will get
  # a very high boost factor, and one for left-anchored wildcard searches,
  # which will return a larger number of hits at a lower boost.
  CustomMunge:
    location_fuzzy:
      - [uppercase]
      - [preg_replace, '/[\s]+/m', "|"]
      - [preg_replace, '/\(/m', "\("]
      - [preg_replace, '/\)/m', "\)"]
      - [preg_replace, '/:/m', "\:"]
      - [preg_replace, '/\*/m', ""]
      - [preg_replace, '/\*/m', ""]
      - [append, "* "]
  QueryFields:
    callnumber_second:
      - [onephrase, 1000]
      - [location_fuzzy, ~]

Callnumber:
  # We use two similar munges here -- one for exact matches, which will get
  # a very high boost factor, and one for left-anchored wildcard searches,
  # which will return a larger number of hits at a lower boost.
  CustomMunge:
    location_fuzzy:
      - [uppercase]
      - [preg_replace, '/[\s]+/m', ""]
      - [preg_replace, '/\*/m', ""]
      #- [preg_replace, '/[\"]/m', ""]
      #- [preg_replace, "/^(.*)\$/", '\"\$1']
      #- [append, "*\""]
      - [append, "* "]
  QueryFields:
    callnumber:
      - [onephrase, 1000]
      - [location_fuzzy, ~]

UDC:
  CustomMunge:
    escape:
      - [preg_replace, "/:/", "\\:"]
      - [preg_replace, "/\\[/", "\\["]
      - [preg_replace, "/\\]/", "\\]"]
      - [preg_replace, "/\\(/", "\\("]
      - [preg_replace, "/\\)/", "\\)"]
      - [preg_replace, '/\\"/', "\\\""]
      - [preg_replace, '/$/m', "\""]
      - [preg_replace, '/^/m', "\""]
  QueryFields:
    udc_str_mv:
      - [escape, ~]
